-- AlterTable
ALTER TABLE "Receipt" ADD COLUMN     "grossWeight" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "netWeight" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tareWeight" DOUBLE PRECISION NOT NULL DEFAULT 0;
